apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::655431895664:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-TmzBe5lY872J
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::655431895664:user/nasa
      username: nasa
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-26T03:23:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1275"
  uid: a4df7aa0-68d8-4e24-a2ae-d731cb27292f


  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::315069654700:user/harish
      username: nasa
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-05T01:35:42Z"
  name: aws-auth
  namespace: kube-system
  uid: eea0273c-8df3-4176-8901-b17003f83095 #don't delete this