apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::655431895664:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-TmzBe5lY872J
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::655431895664:user/nasa
      username: nasa
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-26T03:23:58Z"
  name: aws-auth
  namespace: kube-system
  #uid: a4df7aa0-68d8-4e24-a2ae-d731cb27292f  #don't delete this


  